type User {
  id: ID
  nickname: String!
  email: String!
  create_date: String!
  post(id: ID!): Post
  posts: [Post!]!
  follower(id: ID!): User
  followers: [User!]!
  followee(id: ID!): User
  followees: [User!]!
}

type Post {
  id: ID
  user: User!
  title: String!
  body: String!
  praise_num: Int!
  comment_num: Int!
  create_date: String!
  comment(id: ID!): Comment
  comments: [Comment!]!
}

type Comment {
  id: ID
  user: User!
  post: Post!
  title: String
  body: String!
  create_date: String!
}

type Query {
  user(user_id: ID!): User!
}

type Mutation {
  login(email: String!, pw: String!): Auth
  createUser(nickname: String!, email: String!, pw: String!): User
  removeUser(token: String!, user_id: ID!): Boolean
  follow(token: String!, follower_id: ID!, followee_id: ID!): Boolean
  unfollow(token: String!, follower_id: ID!, followee_id: ID!): Boolean
  createPost(token: String!, user_id: ID!, title: String!, body: String!): Post
  removePost(token: String!, post_id: ID!): Boolean
  updatePost(token: String!, post_id: ID!, title: String, body: String)：Boolean
  createComment(token: String!, user_id: ID!, post_id: ID!, title: String!, body: String!): Comment
  removeComment(token: String!, comment_id: ID!): Boolean
  praisePost(token: String!, post_id: ID!, user_id: ID!): Boolean
  unpraisePost(token: String!, post_id: ID!, user_id: ID!): Boolean
}
